# Generated by Django 3.1.4 on 2022-10-03 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20221002_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='organistion',
            new_name='organisation',
        ),
    ]
